### ISSUE TITLE
Widget creator broken

### ISSUE THREAD

**Issue by apetro** [uPortal-Project/uportal-home#627]
Intended to include a "Widget Creator" such that https://public.my.wisc.edu/web/widget-creator would be a thing. But it's broken.

-----

(This public GitHub issue tracker issue shadows MyUW-local [MUMUP-2914](https://jira.doit.wisc.edu/jira/browse/MUMUP-2914); this shadowing is a small step toward experimenting with better tracking product issues publicly rather than in private MyUW JIRA.)

**Comment by ChristianMurphy** [comment]
:question: is this still an issue? widget creator appears to be functional again.
:arrow_right: If it is still an issue could this move to the widget-creator repo?

**Comment by apetro** [comment]
Not still an issue. Widget Creator broken out into its own project, and [publicly available as deployed](https://my.wisc.edu/widget-creator).
