### ISSUE TITLE
angularjs-portal migration to uPortal-home

### ISSUE THREAD

**Issue by davidmsibley** [uPortal-Project/uportal-home#697]
@UW-Madison-DoIT/uportal-home-committers 

Within the next two weeks, uw-frame and angularjs-portal will be changing names to uPortal-app-framework and uPortal-home as part of our Apereo incubation process.

This will include:
changing the maven groupId and artifactId
moving the repository location to within the [uPortal-Project organization](https://github.com/uPortal-Project) in GitHub

As a developer, you may need to:
update your git remote if you have these projects cloned locally
update maven dependency information in your project's pom.xml

You'll receive more detailed information as we work through the process. If you have any questions or concerns about whether this affects you or how to update your project, please feel free to respond to this issue or email ~the myuw-infra team at myuw-infra@office365.wisc.edu~ the uPortal-home committers at `uportal-dev@`.

Thanks!

**Comment by ChristianMurphy** [comment]
Thanks for the heads up @davidmsibley! :100:

**Comment by ChristianMurphy** [comment]
Related to https://groups.google.com/a/apereo.org/d/topic/uportal-dev/3lFhjXz0aoQ/discussion

**Comment by davidmsibley** [comment]
@UW-Madison-DoIT/uportal-home-committers
I'm looking to cut a pre-move release today or tomorrow. This coincides with needing to cut a release this week to be able to deploy the ABE widget next week.

I'm expecting to include #703 in the release, as it fixes a serious bug.

Any thoughts on whether #699 is good to go? Since time is of the essence, I'd err on the side of not including it if it's not 100%

**Comment by ChristianMurphy** [comment]
Sounds good 👍 
#703 has been merged. ✅ 
#699 only has minor changes requested, so you *could* merge it as is, if there is a rush.

**Comment by davidmsibley** [comment]
https://www.npmjs.com/package/@uportal/home
https://github.com/UW-Madison-DoIT/angularjs-portal/releases/tag/uportal-home-parent-7.0.0
