### ISSUE TITLE
Update TravisCI due to repo move

### ISSUE THREAD

**Issue by davidmsibley** [uPortal-Project/uportal-home#707]
I think it auto-updated for app-framework, here it's still calling itself `uPortal-Project/angularjs-portal` 

I may have tried renaming the repo too soon after transferring ownership? I'm not sure how to get it to rename itself.

**Comment by ChristianMurphy** [comment]
Running sync on Travis CI brings in the updated name. :recycle: 
:white_check_mark: https://travis-ci.org/uPortal-Project/uportal-home
