### ISSUE TITLE
update Coveralls due to repo move

### ISSUE THREAD

**Issue by davidmsibley** [uPortal-Project/uportal-home#708]
new project wants to point to https://coveralls.io/github/uPortal-Project/uportal-home?branch=master

**Comment by ChristianMurphy** [comment]
:link: https://github.com/lemurheavy/coveralls-public/issues/399#issuecomment-128484573

**Comment by davidmsibley** [comment]
I guess I don't have enough permissions on the UW-Madison-DoIT org? @apetro can you go [here](https://coveralls.io/github/UW-Madison-DoIT/angularjs-portal/settings) and sync the project?

**Comment by apetro** [comment]
I don't think the rename sync copes with the re-org. It probably would have worked if it were just a rename within the org.  Anyway, I [turned on Coveralls for `uPortal-Project/uportal-home`](https://coveralls.io/github/uPortal-Project/uportal-home) so maybe that'll start working?

**Comment by ChristianMurphy** [comment]
Thanks @apetro!
