### ISSUE TITLE
Update Greenkeeper due to repo move

### ISSUE THREAD

**Issue by davidmsibley** [uPortal-Project/uportal-home#711]

**Comment by ChristianMurphy** [comment]
@davidmsibley updates to the greenkeeper integration require an organization admin.
/cc @apetro

**Comment by apetro** [comment]
Done: enabled Greenkeeper access to `uPortal home`.

![greenkeeper-for-up-home](https://user-images.githubusercontent.com/952283/30986584-8e40bb3e-a459-11e7-9a39-f52dd54d17e5.png)

**Comment by ChristianMurphy** [comment]
[![Greenkeeper badge](https://badges.greenkeeper.io/uPortal-Project/uportal-home.svg)](https://greenkeeper.io/)

Thanks @apetro!
