### ISSUE TITLE
Do we really need this many badges?

### ISSUE THREAD

**Issue by davidmsibley** [uPortal-Project/uportal-home#712]

**Comment by ChristianMurphy** [comment]
probably not,
Its function is somewhat of a sitemap for where to find the project tooling.
If there is a better way to communicate that information, I'd be happy to +1 :+1:  the PR.

**Comment by davidmsibley** [comment]
:+1:

**Comment by apetro** [comment]
Need? No. But I do think they help keep us honest about our aspirations and realities.
