### ISSUE TITLE
Relax Coveralls threshhold and suppress Code Climate PR status failures

### ISSUE THREAD

**Issue by apetro** [uPortal-Project/uportal-home#727]
We should improve test coverage someday.

In the meantime, Coveralls delivering red Xs to pull requests is demoralizing  and distracting without being helpful.

Therefore **reconfigured Coveralls with cartoonishly low standards about test coverage. Should always pass.** We still get the automatic calc, we can choose to engage with test coverage any time we want, but we stop with the annoyance in the meantime.

(Logged as GitHub issue for transparency.)

**Comment by ChristianMurphy** [comment]
Related to https://github.com/uPortal-Project/uportal-app-framework/issues/574

**Comment by apetro** [comment]
Ditto Code Climate, done.

**Comment by ChristianMurphy** [comment]
> done.
https://github.com/uPortal-Project/uportal-home/issues/727#issuecomment-336184662

@apetro does that mean this ticket is complete and can be closed?

**Comment by apetro** [comment]
Think this is done, yes.
