### ISSUE TITLE
Discussion: Attempt to merge stale branches?

### ISSUE THREAD

**Issue by ChristianMurphy** [uPortal-Project/uportal-home#740]
Hey @uPortal-Project/uportal-home-committers! :wave: 

There are a couple of unmerged branches that have fallen over 300 commits behind the current `master` branch version.
![screencapture-github-uportal-project-uportal-home-branches-stale-1509986663900](https://user-images.githubusercontent.com/3107513/32452608-44843ba0-c2d7-11e7-9389-386306e05ad5.png)

Would it be worth while to attempt to merge these branches? Or should they be closed without merging?

**Comment by ChristianMurphy** [comment]
Invoking lazy consensus.
The plan would be to open PR to `master`, close the PR, then delete the branch.
This would allow the branch to be restored if need be, but clear it from the active references.

**Comment by davidmsibley** [comment]
gh-pages shouldn't be merged. Should probably just be deleted. incubation-status is probably obsolete

**Comment by ChristianMurphy** [comment]
Yep, my plan is not to merge, but to open a PR then close it unmerged, which leaves the option to restore.
![selection_010](https://user-images.githubusercontent.com/3107513/32508946-2d9491b0-c3a9-11e7-8327-ff0224f61e3e.png)

But if the reference isn't needed at all. :thinking: 
Sure, it can be directly closed. :+1:

**Comment by ChristianMurphy** [comment]
Done :white_check_mark: 
Thanks for the info @davidmsibley!
